# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83e825e6b74ff5e6c736f25e0c604d1d4e9955160fa6dbd37f538bd3c6f8df2c9b17f812ca6248b84914b224916f5246e5a575e510c1064dce31cf4b60d65423

test:
  secret_key_base: a719eceb12cbc9cdd8d662b7fede6284d3450b64a0ef16365dc97f46d0fccd140abf70976c80b772bfc58f5443a3cc950dfa43932ebf658033817ae8801fe731

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
